### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Bodix** [aotearoan/neon#153]
Hello! 

Your library is something incredible. It's very beautiful and aesthetically pleasing.

I wanted to use it on my portfolio site. But I'm using Vue 3.
At first, I tried just installing the package and running it, but the console would get an error and the page wouldn't render. 
Then I tried running in compatibility mode as shown in this [guide](https://www.vuemastery.com/blog/vue-3-migration-build/).

Now the page is rendered correctly, but most of the components don't work. For example, NeonLogo works, but NeonButton doesn't. 
The following errors are coming up in the console:
![image](https://user-images.githubusercontent.com/32435284/142397090-44be692b-30db-4bba-ae6a-cfcf34130291.png)
The call stack of many of these errors leads to Neon.

In this regard, I would like to contribute to your library and upgrade it to Vue 3. Since I'm not a web expert (I'm a gamdev), I don't understand at all how to do it and where to start. 

Can you please tell me what to do to make the library work on Vue 3?

**Comment by aotearoan** [comment]
Apologies for the lack of response. I have finally managed to find some time to upgrade to support Vue 3. I have released a package to npm 6.0.0.0-beta.1 which is a first version of Neon using Vue 3. Smooth is currently the only supported theme, the others will be added very soon.

There's a small sample project to see how to use it here - https://github.com/aotearoan/neon-vue3-sample

**Comment by aotearoan** [comment]
Vue 3 support is now out of beta. There's a new approach to theming using CSS variables. The latest version is 9.2.2. Closing this issue as a result
