### ISSUE TITLE
How will I use your package

### ISSUE THREAD

**Issue by TUCA33** [aotearoan/neon#77]
hi first of all i can't use your package.
my transactions
```
vue init webpack-simle ./
immediately after
npm install @aotearoan/neon
```

but now I do not understand how to use your package.
In the "app.vue" file

<neon-footer>
  <span> Footer content </span>
</neon-footer>
it doesn't work when i write

can you help me

**Comment by aotearoan** [comment]
Hi @TUCA33 please read through the getting started section. You should find what you need there - https://aotearoan.github.io/neon/for-developers/getting-started.

If you have a specific issue please post it here with the error and steps to reproduce.

**Comment by TUCA33** [comment]
I finished like this and now I don't know what to do.
[Photo](https://ibb.co/0KF3Gnk)

**Comment by aotearoan** [comment]
You need to import the SASS also - 

https://aotearoan.github.io/neon/for-developers/getting-started#sass

**Comment by TUCA33** [comment]
Well I have included your package in the .js file, but where do I define it?

**Comment by aotearoan** [comment]
If you’re not sure how to work with SASS in Vue either ready the beginners guide to Vue or join the Vue Discord group.

The instructions here should be clear enough to somebody familiar with Vue and SASS - https://aotearoan.github.io/neon/for-developers/getting-started#sass

I’m closing this ticket as this is not an issue with Neon (happy to help if you find a specific issue though).
